#!/usr/bin/env python3
"""
Daily Market Pulse Bot - Cloud Version
Runs on GitHub Actions with Claude API for intelligent market analysis.
"""

import os
import requests
from datetime import datetime

# Get secrets from environment variables
BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")

def get_market_data():
      """Fetch current market data from free APIs."""
      market_info = []

    indices = {
              "S&P 500": "^GSPC",
              "Dow Jones": "^DJI",
              "Nasdaq": "^IXIC",
              "10Y Treasury": "^TNX",
              "VIX": "^VIX",
              "Gold": "GC=F",
              "Oil (WTI)": "#C!L/=uFs"r,/
b i n / e n v   p"yBtihtocno3i
n""":" 
"DBaTiCl-yU SMDa"r,k
e t   P u}l
s
e   B o tf o-r  Cnlaomued,  Vseyrmsbiooln )u.rgreetn(t" rmeasruklett" ,d a[t{a} ]f)r[o0m] 
f r e e   A P I s . " " " 
      m emtaar k=e tr_eisnuflot .=g e[t](
      "
      m e t a "i,n d{i}c)e
      s   =   { 
                       " S &pPr i5c0e0 "=:  m"e^tGaS.PgCe"t,(
                       " r e g u l a r M"aDrokwe tJPorniecse"":) 
                       " ^ D J I " , 
                                        "pNraesvd_acql"o:s e" ^=I XmIeCt"a,.
                                        g e t ( " p r e v"i1o0uYs CTlroesaes"u)r
                                        y " :   " ^ T N X " , 
                                                  i f   p"rViIcXe" :a n"d^ VpIrXe"v,_
                                                  c l o s e : 
                                                      " G o l d " :   " G C = F " , 
                                                            c h a n g e"_Opiclt  (=W T(I()p"r:i c"eC L-= Fp"r,e
                                                            v _ c l o s e )  "/B iptrceovi_nc"l:o s"eB)T C*- U1S0D0"
                                                            , 
                                                                     } 

                                                                               f o r   n a m ei,f  snyammbeo l= =i n" 1i0nYd iTcreesa.siutreym"s:(
                                                                               ) : 
                                                                                                t r y : 
                                                                                                                  m a r kuertl_ i=n ffo".hatptppesn:d/(/fq"u{enraym1e.}f:i n{apnrciec.ey:a.h2ofo}.%c o(m{/cvh8a/nfgien_apnccte:/+c.h2afr}t%/){"s)y
                                                                                                                  m b o l } " 
                                                                                                                                           h eealdiefr sp r=i c{e" U>s e1r0-0A0g:e
                                                                                                                                           n t " :   " M o z i l l a / 5 . 0 " } 
                                                                                                                                                     m a r k e t _ irnefsop.oanpspee n=d (rfe"q{uneasmtes}.:g e{tp(ruircle,: ,h.e0afd}e r(s{=chheaandgeer_sp,c tt:i+m.e2ofu}t%=)1"0))
                                                                                                                                                     
                                                                                                                                                                              i f   r e s p oenlssee.:s
                                                                                                                                                                              t a t u s _ c o d e   = =   2 0 0 : 
                                                                                                                                                                                          m a r k e t _ i n f od.aatpap e=n dr(efs"p{onnasmee.}j:s o{np(r)i
                                                                                                                                                                                          c e : . 2 f }   ( { c h a n g e _rpecstu:l+t. 2=f }d%a)t"a).
                                                                                                                                                                                          g e t ( " c h a retx"c,e p{t} )E.xgceetp(t"iroens ualst "e,: 
                                                                                                                                                                                          [ { } ] ) [ 0 ] 
                                                                                                                                                                                                  p r i n t ( f " E r r o rm efteat c=h irnegs u{lnta.mgee}t:( "{mee}t"a)"
                                                                                                                                                                                                  ,
                                                                                                                                                                                                    { } ) 
                                                                                                                                                                                                    r e t u r n   m a r k e t _ i n fpor
                                                                                                                                                                                                    i
                                                                                                                                                                                                    c
                                                                                                                                                                                                    ed e=f  mgeetnae.rgaette(_"braesgiucl_aarnMaalrykseitsP(rmiacrek"e)t
                                                                                                                                                                                                    _ d a t a ) : 
                                                                                                                                                                                                             " " " G epnreerva_tcel obsaes i=c  maentaal.ygseits( "wpirtehvoiuotu sACIl.o"s"e""
                                                                                                                                                                                                             ) 
                                                                                                                                                                                                                   t o d a y   =   d a t e t iimfe .pnroiwc(e) .asntdr fptriemve_(c"l%oAs,e :%
                                                                                                                                                                                                                   B   % d ,   % Y " ) 
                                                                                                                                                                                                                    
                                                                                                                                                                                                                             m e s s acghea n=g ef_"p"c"t📊  D=A I(L(Yp rMiAcReK E-T  pPrUeLvS_Ec
                                                                                                                                                                                                                             l📅o s{et)o d/a yp}r
                                                                                                                                                                                                                             e
                                                                                                                                                                                                                             v"_"c"l
                                                                                                                                                                                                                             o
                                                                                                                                                                                                                             s e )   *i f1 0m0a
                                                                                                                                                                                                                             r k e t _ d a t a : 
                                                                                                                                                                                                                                              m eisfs angaem e+ == =" 📈 "M1A0RYK ETTr eOaVsEuRrVyI"E:W
                                                                                                                                                                                                                                              : \ n " 
                                                                                                                                                                                                                                                               f o r   d a t a   i n  mmaarrkkeett__idnaftoa.:a
                                                                                                                                                                                                                                                               p p e n d ( f " { n a m em}e:s s{apgrei c+e=: .f2"f•} %{ d(a{tcah}a\nng"e
                                                                                                                                                                                                                                                               _ p c t : + . 2 fm}e%s)s"a)g
                                                                                                                                                                                                                                                               e   + =   " \ n " 
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                         m e s s a geel i+f=  p"r"i"c🔟 e1 0>  T1H0I0N0G:S
                                                                                                                                                                                                                                                                           T O   W A T C H   T O D A Y : 
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                             1 ️ ⃣  P R E -mMaArRkKeEtT_ iFnUfToU.RaEpSp e-n dC(hfe"c{kn aimned}e:x  {fpurtiucree:s for early direction signals.
                                                                                                                                                                                                                                                                             2️⃣ ECONOMIC CALENDAR - Review scheduled data releases.
                                                                                                                                                                                                                                                                             3️⃣ FED WATCH - Monitor any Fed official speeches.
                                                                                                                                                                                                                                                                             4️⃣ EARNINGS REPORTS - Track companies reporting today.
                                                                                                                                                                                                                                                                             5️⃣ BOND YIELDS - Watch 10-year Treasury for risk signals.
                                                                                                                                                                                                                                                                             6️⃣ SECTOR ROTATION - Identify leading/lagging sectors.
                                                                                                                                                                                                                                                                             7️⃣ GLOBAL MARKETS - Check Europe/Asia closes.
                                                                                                                                                                                                                                                                             8️⃣ GEOPOLITICS - Monitor trade/policy news.
                                                                                                                                                                                                                                                                             9️⃣ COMMODITIES - Track oil, gold for inflation signals.
                                                                                                                                                                                                                                                                             🔟 VOLATILITY (VIX) - Monitor market stress levels.
                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                             💡 Stay informed, stay ahead.
                                                                                                                                                                                                                                                                             🤖 Daily Market Pulse Bot"""
                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                 return message
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                 def send_telegram_message(message):
                                                                                                                                                                                                                                                                                     """Send message to Telegram group."""
                                                                                                                                                                                                                                                                                         url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                             payload = {
                                                                                                                                                                                                                                                                                                     "chat_id": CHAT_ID,
                                                                                                                                                                                                                                                                                                             "text": message,
                                                                                                                                                                                                                                                                                                                     "parse_mode": "Markdown",
                                                                                                                                                                                                                                                                                                                             "disable_web_page_preview": True
                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                     try:
                                                                                                                                                                                                                                                                                                                                             response = requests.post(url, json=payload, timeout=30)
                                                                                                                                                                                                                                                                                                                                                     result = response.json()
                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                             if result.get("ok"):
                                                                                                                                                                                                                                                                                                                                                                         print("Message sent successfully!")
                                                                                                                                                                                                                                                                                                                                                                                     return True
                                                                                                                                                                                                                                                                                                                                                                                             else:
                                                                                                                                                                                                                                                                                                                                                                                                         error = result.get("description", "Unknown error")
                                                                                                                                                                                                                                                                                                                                                                                                                     print(f"Failed: {error}")
                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                 # Try with -100 prefix for supergroups
                                                                                                                                                                                                                                                                                                                                                                                                                                             if "chat not found" in error.lower():
                                                                                                                                                                                                                                                                                                                                                                                                                                                             payload["chat_id"] = f"-100{CHAT_ID.lstrip('-')}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             response = requests.post(url, json=payload, timeout=30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if response.json().get("ok"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 print("Sent with -100 prefix!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             print(f"Error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         print("Daily Market Pulse Bot (Cloud)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             print(f"Running at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if not BOT_TOKEN or not CHAT_ID:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         print("Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     print("Fetching market data...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         market_data = get_market_data()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             print(f"Got {len(market_data)} data points")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 print("Generating analysis...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     message = generate_basic_analysis(market_data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         print("Sending to Telegram...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             success = send_telegram_message(message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return success
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     success = main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         exit(0 if success else 1)
iRnu nisn doinc eGsi.tiHtuebm sA(c)t:i
o n s   w i t h  tCrlya:u
d e   A P I   f o r   i nutrell l=i gfe"nhtt tmpasr:k/e/tq uaenrayl1y.sfiisn.a
n"c"e".
y
aihmopoo.rcto mo/sv
8i/mfpionratn cree/qcuheasrtts/
{fsryommb odla}t"e
t i m e   i m p o r t   dhaetaedteirmse 
=
 #{ "GUeste rs-eAcgreentts" :f r"oMmo zeinlvliar/o5n.m0e"n}t
   v a r i a b l e s 
    B OrTe_sTpOoKnEsNe  ==  orse.qeunevsitrso.ng.egte(tu(r"lT,E LhEeGaRdAeMr_sB=OhTe_aTdOeKrEsN," )t
    iCmHeAoTu_tI=D1 0=) 
    o s . e n v i r o n . g eitf( "rTeEsLpEoGnRsAeM._sCtHaAtTu_sI_Dc"o)d
    eA N=T=H R2O0P0I:C
    _ A P I _ K E Y   =   o s . e n vdiartoan .=g erte(s"pAoNnTsHeR.OjPsIoCn_(A)P
    I _ K E Y " ) 

      d e f   g e t _rmeasruklett _=d adtaat(a).:g
      e t ( " c"h"a"rFte"t,c h{ }c
